/**
 * Finding-to-ADO-thread mapping and summary generation.
 *
 * Handles two responsibilities:
 * 1. Posting a file's findings as inline PR comments, filtering out
 *    findings with invalid line numbers (Pitfall 3 defense).
 * 2. Building the final PR-level summary markdown with severity counts.
 */

import { postInlineComment } from '@/lib/ado-api/threads';
import type { Finding } from './schemas';
import type { SingleFileResult } from './types';
import type { PrInfo } from '@/shared/types';

/**
 * Post a file's findings as inline comments on the PR.
 *
 * Validates each finding's line number before posting. Findings with
 * invalid line numbers (non-positive integers) are dropped silently.
 * Individual post failures are caught and counted as dropped -- they
 * do not stop remaining findings from being posted.
 *
 * @param prInfo - Parsed PR URL components
 * @param filePath - Path to the file within the repository
 * @param findings - Array of findings from the LLM review
 * @param iterationId - PR iteration ID for comment context
 * @returns Counts of successfully posted and dropped findings
 */
export async function postFileFindings(
  prInfo: PrInfo,
  filePath: string,
  findings: Finding[],
  iterationId: number,
): Promise<{ posted: number; dropped: number }> {
  let posted = 0;
  let dropped = 0;

  for (const finding of findings) {
    // Validate line number: must be a positive integer
    if (!Number.isInteger(finding.line) || finding.line <= 0) {
      dropped++;
      continue;
    }

    try {
      await postInlineComment(prInfo, filePath, finding, iterationId);
      posted++;
    } catch (error) {
      console.error(
        `[PEP Review] Failed to post comment for ${filePath}:${finding.line}:`,
        error,
      );
      dropped++;
    }
  }

  return { posted, dropped };
}

/**
 * Build a markdown summary of the review results for a PR-level comment.
 *
 * Generates a formatted table showing each reviewed file, its finding
 * counts by severity, and any errors encountered. Skipped files are
 * not included in the table.
 *
 * @param results - Array of per-file review results
 * @param prTitle - The PR title for the summary header
 * @returns Formatted markdown string for the summary comment
 */
export function buildSummaryMarkdown(
  results: SingleFileResult[],
  prTitle: string,
): string {
  // Tally totals across all results
  let reviewedCount = 0;
  let errorCount = 0;
  let totalFindings = 0;
  let criticalTotal = 0;
  let warningTotal = 0;
  let infoTotal = 0;

  for (const result of results) {
    if (result.status === 'error') {
      errorCount++;
    } else if (result.status === 'success') {
      reviewedCount++;
      for (const f of result.findings) {
        totalFindings++;
        if (f.severity === 'Critical') criticalTotal++;
        else if (f.severity === 'Warning') warningTotal++;
        else infoTotal++;
      }
    }
  }

  // Build the file results table rows
  const tableRows = results
    .filter((r) => r.status !== 'skipped')
    .map((result) => {
      if (result.status === 'error') {
        const errMsg = result.error
          ? result.error.slice(0, 80)
          : 'Unknown error';
        return `| \`${result.filePath}\` | - | Error: ${errMsg} |`;
      }

      const count = result.findings.length;
      if (count === 0) {
        return `| \`${result.filePath}\` | 0 | Clean |`;
      }

      // Count severities for this file
      let c = 0;
      let w = 0;
      let i = 0;
      for (const f of result.findings) {
        if (f.severity === 'Critical') c++;
        else if (f.severity === 'Warning') w++;
        else i++;
      }

      // Build abbreviated severity string (only non-zero)
      const parts: string[] = [];
      if (c > 0) parts.push(`${c}C`);
      if (w > 0) parts.push(`${w}W`);
      if (i > 0) parts.push(`${i}I`);
      const severityStr = parts.length > 0 ? ` (${parts.join(', ')})` : '';

      return `| \`${result.filePath}\` | ${count}${severityStr} | Reviewed |`;
    })
    .join('\n');

  const skippedCount = results.filter((r) => r.status === 'skipped').length;

  return `## PEP Review Summary

**PR:** ${prTitle}

### Overview
- **Files reviewed:** ${reviewedCount}
- **Files skipped:** ${skippedCount} (non-code files)
- **Files with errors:** ${errorCount}
- **Total findings:** ${totalFindings} (${criticalTotal} Critical, ${warningTotal} Warning, ${infoTotal} Info)

### File Results

| File | Findings | Status |
|------|----------|--------|
${tableRows}

---
*Generated by PEP Review*`;
}
